In [5]:
#dataframe
import pandas as pd
import numpy as np
data = {
    'Name': ["preeti","bob","Me","Eve","adu"],
    'age':[23,30,35,np.nan,20],
    'dept':['HR','IT','finace','It',"HR"],
    'sal':[23000,45000,70000,np.nan,34000]
}

In [6]:
data

{'Name': ['preeti', 'bob', 'Me', 'Eve', 'adu'],
 'age': [23, 30, 35, nan, 20],
 'dept': ['HR', 'IT', 'finace', 'It', 'HR'],
 'sal': [23000, 45000, 70000, nan, 34000]}

In [8]:
df = pd.DataFrame(data)
df

     Name   age    dept      sal
0  preeti  23.0      HR  23000.0
1     bob  30.0      IT  45000.0
2      Me  35.0  finace  70000.0
3     Eve   NaN      It      NaN
4     adu  20.0      HR  34000.0

In [9]:
df.head(2)

     Name   age dept      sal
0  preeti  23.0   HR  23000.0
1     bob  30.0   IT  45000.0

In [10]:
df.tail(3)

  Name   age    dept      sal
2   Me  35.0  finace  70000.0
3  Eve   NaN      It      NaN
4  adu  20.0      HR  34000.0

In [11]:
#iloc and loc
df.iloc[1:3]

  Name   age    dept      sal
1  bob  30.0      IT  45000.0
2   Me  35.0  finace  70000.0

In [12]:
df.loc[1:3,["age","dept"]]

    age    dept
1  30.0      IT
2  35.0  finace
3   NaN      It

In [15]:
df.loc[1:3,:2] #row , col

TypeError: cannot do slice indexing on Index with these indexers [2] of type int

In [16]:
df.iloc[1:3,:3] #row,col

  Name   age    dept
1  bob  30.0      IT
2   Me  35.0  finace

In [17]:
#for only one col

df["age"]

0    23.0
1    30.0
2    35.0
3     NaN
4    20.0
Name: age, dtype: float64

In [19]:
df[["age","Name"]]

    age    Name
0  23.0  preeti
1  30.0     bob
2  35.0      Me
3   NaN     Eve
4  20.0     adu

In [20]:
df.drop("age",axis=1)

     Name    dept      sal
0  preeti      HR  23000.0
1     bob      IT  45000.0
2      Me  finace  70000.0
3     Eve      It      NaN
4     adu      HR  34000.0

In [21]:
df #in original no change happen

     Name   age    dept      sal
0  preeti  23.0      HR  23000.0
1     bob  30.0      IT  45000.0
2      Me  35.0  finace  70000.0
3     Eve   NaN      It      NaN
4     adu  20.0      HR  34000.0

In [22]:
#if you want to change in origianl use inplace=True

df.drop('age',axis=1,inplace =True)

In [23]:
df

     Name    dept      sal
0  preeti      HR  23000.0
1     bob      IT  45000.0
2      Me  finace  70000.0
3     Eve      It      NaN
4     adu      HR  34000.0

In [24]:
df.shape

(5, 3)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   dept    5 non-null      object
 2   sal     4 non-null      float64
dtypes: float64(1), object(2)
memory usage: 248.0+ bytes

In [30]:
df.describe()

                sal
count      4.000000
mean   43000.000000
std    20116.328359
min    23000.000000
25%    31250.000000
50%    39500.000000
75%    51250.000000
max    70000.000000

In [31]:
d1 = {
    "name":["preeti","Riya","amit"],
    "age":[23,45,25],
    "city":["banglore","pune","belgaum"]
}

In [34]:
df = pd.DataFrame(d1)
df

     name  age      city
0  preeti   23  banglore
1    Riya   45      pune
2    amit   25   belgaum

In [35]:
df.head(3)

     name  age      city
0  preeti   23  banglore
1    Riya   45      pune
2    amit   25   belgaum

In [36]:
df.tail(2)

   name  age     city
1  Riya   45     pune
2  amit   25  belgaum

In [39]:
df.shape

(3, 3)

In [40]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes

In [44]:
df.dtypes

name    object
age      int64
city    object
dtype: object

In [45]:
df.describe()

             age
count   3.000000
mean   31.000000
std    12.165525
min    23.000000
25%    24.000000
50%    25.000000
75%    35.000000
max    45.000000