In [14]:
#broadcasting
import pandas as pd
import numpy as np
d1 = {
    "Name":["preeti","ravi","radhika","adu","akk"],
    "age":[34,54,22,33,44],
    "Dept":["HR","fiance","Teacher",np.nan,"HR"],
    "salary":[23000,34000,np.nan,34888,20000]
}

In [15]:
d = pd.DataFrame(d1)
d

      Name  age     Dept   salary
0   preeti   34       HR  23000.0
1     ravi   54   fiance  34000.0
2  radhika   22  Teacher      NaN
3      adu   33      NaN  34888.0
4      akk   44       HR  20000.0

In [16]:
d["salary"] = d["salary"]+5000

In [17]:
d["salary"]

0    28000.0
1    39000.0
2        NaN
3    39888.0
4    25000.0
Name: salary, dtype: float64

In [18]:
#renaming coloums in data

d.rename(columns = {"name":"Name"},inplace = True)

In [19]:
d

      Name  age     Dept   salary
0   preeti   34       HR  28000.0
1     ravi   54   fiance  39000.0
2  radhika   22  Teacher      NaN
3      adu   33      NaN  39888.0
4      akk   44       HR  25000.0

In [20]:
d["salary"].unique()

array([28000., 39000.,    nan, 39888., 25000.])

In [21]:
d["Dept"].unique()

array(['HR', 'fiance', 'Teacher', nan], dtype=object)

In [23]:
d["Dept"].value_counts()

HR         2
fiance     1
Teacher    1
Name: Dept, dtype: int64

In [24]:
d["Promoted salary"] = d["salary"]*10

In [25]:
d

      Name  age     Dept   salary  Promoted salary
0   preeti   34       HR  28000.0         280000.0
1     ravi   54   fiance  39000.0         390000.0
2  radhika   22  Teacher      NaN              NaN
3      adu   33      NaN  39888.0         398880.0
4      akk   44       HR  25000.0         250000.0