In [5]:
#data cleaning
import numpy as np
import pandas as pd

d1 = {
    "Name":["preeti","ram","Ravi","kavi","shree"],
    "Age":[23,43,26,57,np.nan],
    "Dept":["Hr","Teacher","Fiance",np.nan,"Hr"],
    "Sal":[34000,45000,np.nan,450000,34000]
}

In [6]:
d = pd.DataFrame(d1)

In [7]:
d

     Name   Age     Dept       Sal
0  preeti  23.0       Hr   34000.0
1     ram  43.0  Teacher   45000.0
2    Ravi  26.0   Fiance       NaN
3    kavi  57.0      NaN  450000.0
4   shree   NaN       Hr   34000.0

In [8]:
d.isnull().sum()

Name    0
Age     1
Dept    1
Sal     1
dtype: int64

In [9]:
#remove the all null values
d.dropna()

     Name   Age     Dept      Sal
0  preeti  23.0       Hr  34000.0
1     ram  43.0  Teacher  45000.0

In [10]:
d

     Name   Age     Dept       Sal
0  preeti  23.0       Hr   34000.0
1     ram  43.0  Teacher   45000.0
2    Ravi  26.0   Fiance       NaN
3    kavi  57.0      NaN  450000.0
4   shree   NaN       Hr   34000.0

In [12]:
d.dropna(how = "any") #any row that had null values

     Name   Age     Dept      Sal
0  preeti  23.0       Hr  34000.0
1     ram  43.0  Teacher  45000.0

In [14]:
d.dropna(how = "all") #if all the values in any row are null then drop

     Name   Age     Dept       Sal
0  preeti  23.0       Hr   34000.0
1     ram  43.0  Teacher   45000.0
2    Ravi  26.0   Fiance       NaN
3    kavi  57.0      NaN  450000.0
4   shree   NaN       Hr   34000.0

In [16]:
#missiing values getting rid - dropna(),filling themup - fillna()

d.fillna(0)

     Name   Age     Dept       Sal
0  preeti  23.0       Hr   34000.0
1     ram  43.0  Teacher   45000.0
2    Ravi  26.0   Fiance       0.0
3    kavi  57.0        0  450000.0
4   shree   0.0       Hr   34000.0

In [17]:
d["Age"].fillna(d["Age"].mean())

0    23.00
1    43.00
2    26.00
3    57.00
4    37.25
Name: Age, dtype: float64

In [19]:
#forward fill backward fill


d["Age"].fillna(method = "ffill")

0    23.0
1    43.0
2    26.0
3    57.0
4    57.0
Name: Age, dtype: float64

In [20]:
d["Sal"].fillna(method = "bfill")

0     34000.0
1     45000.0
2    450000.0
3    450000.0
4     34000.0
Name: Sal, dtype: float64

d["Name"].replace("Preeti","murali")

In [22]:
d["Name"].replace("preeti","murali")

0    murali
1       ram
2      Ravi
3      kavi
4     shree
Name: Name, dtype: object

In [25]:
d["Name"]=d["Name"].replace("preeti","murali")

In [26]:
d

     Name   Age     Dept       Sal
0  murali  23.0       Hr   34000.0
1     ram  43.0  Teacher   45000.0
2    Ravi  26.0   Fiance       NaN
3    kavi  57.0      NaN  450000.0
4   shree   NaN       Hr   34000.0